application: contrastrx
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /(.*\.(json|gif|png|jpg|ico|js|css|manifest))
  static_files: \1
  upload: (.*\.(json|gif|png|jpg|ico|js|css|manifest))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
